# Generated by Django 2.1.3 on 2018-11-27 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigrationform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_val', models.CharField(max_length=200)),
                ('for_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immigrationform.DocumentAttribute')),
            ],
        ),
        migrations.CreateModel(
            name='FreeResponseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='immigrationform.Question')),
                ('current_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immigrationform.FreeResponse')),
            ],
            bases=('immigrationform.question',),
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='immigrationform.Question')),
                ('current_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immigrationform.MultiChoiceResponse')),
            ],
            bases=('immigrationform.question',),
        ),
        migrations.CreateModel(
            name='PolarQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='immigrationform.Question')),
                ('current_answer', models.BooleanField()),
                ('false_score', models.ManyToManyField(related_name='false_scores', to='immigrationform.DocumentAttrValue')),
                ('true_score', models.ManyToManyField(related_name='true_scores', to='immigrationform.DocumentAttrValue')),
            ],
            bases=('immigrationform.question',),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_scores',
        ),
        migrations.RemoveField(
            model_name='question',
            name='active_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_score',
            field=models.ManyToManyField(to='immigrationform.DocumentAttrValue'),
        ),
    ]
