# Generated by Django 2.1.3 on 2018-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigrationform', '0002_auto_20181127_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeresponsequestion',
            name='current_answer',
        ),
        migrations.RemoveField(
            model_name='multichoicequestion',
            name='current_answer',
        ),
        migrations.RemoveField(
            model_name='multichoiceresponse',
            name='choice_code',
        ),
        migrations.RemoveField(
            model_name='multichoiceresponse',
            name='choice_val',
        ),
        migrations.RemoveField(
            model_name='polarquestion',
            name='current_answer',
        ),
        migrations.AddField(
            model_name='multichoiceresponse',
            name='answer_val',
            field=models.TextField(default=''),
        ),
    ]
