# Generated by Django 2.1.3 on 2018-12-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigrationform', '0003_auto_20181127_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CharMultiResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immigrationform.Character')),
                ('for_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immigrationform.MultiChoiceQuestion')),
                ('with_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immigrationform.MultiChoiceResponse')),
            ],
        ),
        migrations.CreateModel(
            name='CharPolarResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_response', models.BooleanField()),
                ('by_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immigrationform.Character')),
                ('for_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immigrationform.PolarQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='PolarResponse',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='immigrationform.Answer')),
            ],
            bases=('immigrationform.answer',),
        ),
        migrations.AddField(
            model_name='character',
            name='multi_choice_answers',
            field=models.ManyToManyField(through='immigrationform.CharMultiResponse', to='immigrationform.MultiChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='character',
            name='polar_answers',
            field=models.ManyToManyField(through='immigrationform.CharPolarResponse', to='immigrationform.PolarQuestion'),
        ),
    ]
