# Generated by Django 2.1.3 on 2018-12-06 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigrationform', '0004_auto_20181204_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charmultiresponse',
            name='with_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immigrationform.Answer'),
        ),
    ]
